export const data = [
  [
    {
      name: 'Азиаткая курица',
      price: '17',
      image: require('../assets/products/meal_asia_chicken.jpeg'),
      count: 1,
      weight: '300',
    },
    {
      name: 'Курица на гриле',
      price: '12',
      image: require('../assets/products/meal_chicken_gril.jpeg'),
      count: 1,
      weight: '350',
    },
    {
      name: 'Рамён',
      price: '20',
      image: require('../assets/products/meal_fried_ramen.jpeg'),
      count: 1,
      weight: '320',
    },
    {
      name: 'Стейк Нью Йорк',
      price: '30',
      image: require('../assets/products/meal_stake_newyork.jpeg'),
      count: 1,
      weight: '400',
    },
    {
      name: 'Турецкая сач-тава',
      price: '22',
      image: require('../assets/products/meal_turkey_sach_tava.jpeg'),
      count: 1,
      weight: '450',
    },
  ],
  [
    {
      name: 'Паста алфредо',
      price: '18',
      image: require('../assets/products/pasta_alfredo.jpeg'),
      count: 1,
      weight: '300',
    },
    {
      name: 'Паста феттучине',
      price: '16',
      image: require('../assets/products/pasta_fettuchine.jpeg'),
      count: 1,
      weight: '300',
    },
    {
      name: 'Паста фудей',
      price: '15',
      image: require('../assets/products/pasta_fudey.jpeg'),
      count: 1,
      weight: '310',
    },
    {
      name: 'Паста карбанаро',
      price: '18',
      image: require('../assets/products/pasta_karbanaro.jpeg'),
      count: 1,
      weight: '370',
    },
    {
      name: 'Паста милан',
      price: '18',
      image: require('../assets/products/pasta_milano.jpeg'),
      count: 1,
      weight: '300',
    },
    {
      name: 'Паста труфель',
      price: '20',
      image: require('../assets/products/pasta_trufel.jpeg'),
      count: 1,
      weight: '340',
    },
  ],
  [
    {
      name: 'Бонфиле пицца',
      price: '14',
      image: require('../assets/products/picca_bonfile.jpeg'),
      count: 1,
      weight: '400',
    },
    {
      name: 'Буффало пицца',
      price: '18',
      image: require('../assets/products/picca_buffalo.jpeg'),
      count: 1,
      weight: '410',
    },
    {
      name: 'Чизбургер пицца',
      price: '13',
      image: require('../assets/products/picca_cheeseburger.jpeg'),
      count: 1,
      weight: '430',
    },
    {
      name: 'Чиккен пицца',
      price: '12',
      image: require('../assets/products/picca_chicken.jpeg'),
      count: 1,
      weight: '400',
    },
    {
      name: 'Шоколадная пицца',
      price: '14',
      image: require('../assets/products/picca_chocolate.jpeg'),
      count: 1,
      weight: '450',
    },
    {
      name: 'Куатто пицца',
      price: '15',
      image: require('../assets/products/picca_cuatto.jpeg'),
      count: 1,
      weight: '460',
    },
    {
      name: 'Кебаб пицца',
      price: '14',
      image: require('../assets/products/picca_kebab.jpeg'),
      count: 1,
      weight: '490',
    },
    {
      name: 'Маргарита пицца',
      price: '6',
      image: require('../assets/products/picca_margarita.jpeg'),
      count: 1,
      weight: '390',
    },
    {
      name: 'Пепперони пицца',
      price: '10',
      image: require('../assets/products/picca_pepperoni.jpeg'),
      count: 1,
      weight: '410',
    },
    {
      name: 'Socials пицца',
      price: '9',
      image: require('../assets/products/picca_socials.jpeg'),
      count: 1,
      weight: '380',
    },
  ],
  [
    {
      name: 'Куриный салат',
      price: '9',
      image: require('../assets/products/salat_chicken.jpeg'),
      count: 1,
      weight: '210',
    },
    {
      name: 'Турецкий салат Чобан',
      price: '6',
      image: require('../assets/products/salat_choban.jpeg'),
      count: 1,
      weight: '220',
    },
    {
      name: 'Салат из говядины',
      price: '10',
      image: require('../assets/products/salat_cow.jpeg'),
      count: 1,
      weight: '250',
    },
    {
      name: 'Фалафель салат',
      price: '7',
      image: require('../assets/products/salat_falafel.jpeg'),
      count: 1,
      weight: '240',
    },
    {
      name: 'Фруктовый салат',
      price: '6',
      image: require('../assets/products/salat_fruits.jpeg'),
      count: 1,
      weight: '250',
    },
    {
      name: 'Греческий Салат',
      price: '6',
      image: require('../assets/products/salat_greece.jpeg'),
      count: 1,
      weight: '210',
    },
    {
      name: 'Куриный кобб салат',
      price: '10',
      image: require('../assets/products/salat_kob.jpeg'),
      count: 1,
      weight: '215',
    },
    {
      name: 'Стейк салат',
      price: '9',
      image: require('../assets/products/salat_stake.jpeg'),
      count: 1,
      weight: '300',
    },
    {
      name: 'Суперфуд салат',
      price: '8',
      image: require('../assets/products/salat_superfood.jpeg'),
      count: 1,
      weight: '290',
    },
    {
      name: 'Тайский салат с говядиной и баклажанами',
      price: '11',
      image: require('../assets/products/salat_tai.jpeg'),
      count: 1,
      weight: '285',
    },
    {
      name: 'Салат нисуаз из тунца',
      price: '14',
      image: require('../assets/products/salat_tunca.jpeg'),
      count: 1,
      weight: '215',
    },
  ],
  [
    {
      name: 'Чечевичный суп',
      price: '4',
      image: require('../assets/products/soup_chechevitsa.jpeg'),
      count: 1,
      weight: '250',
    },
    {
      name: 'Куриный суп с лапшой',
      price: '4',
      image: require('../assets/products/soup_lapsha.jpeg'),
      count: 1,
      weight: '250',
    },
    {
      name: 'Тыквенный суп',
      price: '5',
      image: require('../assets/products/soup_pumpkin.jpeg'),
      count: 1,
      weight: '250',
    },
    {
      name: 'Суп рамен с говядиной',
      price: '16',
      image: require('../assets/products/soup_ramen.jpeg'),
      count: 1,
      weight: '280',
    },
    {
      name: 'Суп Том Ям',
      price: '15',
      image: require('../assets/products/soup_tomyam.jpeg'),
      count: 1,
      weight: '240',
    },
  ],
  [
    {
      name: 'Вишневый',
      price: '20',
      image: require('../assets/products/water_cherry.jpeg'),
      count: 1,
      weight: '110',
    },
    {
      name: 'Милкшейк орео',
      price: '7',
      image: require('../assets/products/water_milkshakeoreo.png'),
      count: 1,
      weight: '130',
    },
    {
      name: 'Милкшейк клубничный',
      price: '9',
      image: require('../assets/products/water_milshakestrawberry.png'),
      count: 1,
      weight: '125',
    },
    {
      name: 'Клубничный мохито',
      price: '5',
      image: require('../assets/products/water_moxito.png'),
      count: 1,
      weight: '130',
    },
    {
      name: 'Зеленый смузи',
      price: '4',
      image: require('../assets/products/water_smuzi.jpeg'),
      count: 1,
      weight: '105',
    },
  ],
];
